FROM golang:1.22.0-bookworm

RUN apt-get update -y
RUN apt-get install git -y
RUN apt-get install build-essential -y
RUN apt-get install libc6 -y
RUN apt-get install jq -y

RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- --default-toolchain stable -y

ENV PATH=/root/.cargo/bin:$PATH
