version: '3'

services:
  evmosnodelocal:
    entrypoint: /usr/bin/evmosd  start --home /root/.evmosd --pruning=nothing --log_level info  --minimum-gas-prices=0.0001aevmos  --json-rpc.gas-cap=50000000  --json-rpc.api eth,txpool,net,web3  --log_format json
